[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:37: The specified exception-handler method handleIt1 contains a forward named "gotoError" which conflicts with a forward in exception-handler handleIt2.
public class Controller extends PageFlowController
       ^
[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:37: The specified exception-handler method handleIt1 contains a forward named "gotoError" which conflicts with a forward in exception-handler handleIt3.
public class Controller extends PageFlowController
       ^
[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:37: The specified exception-handler method handleIt2 contains a forward named "gotoError" which conflicts with a forward in exception-handler handleIt1.
public class Controller extends PageFlowController
       ^
[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:37: The specified exception-handler method handleIt2 contains a forward named "gotoError" which conflicts with a forward in exception-handler handleIt3.
public class Controller extends PageFlowController
       ^
[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:37: The specified exception-handler method handleIt3 contains a forward named "gotoError" which conflicts with a forward in exception-handler handleIt1.
public class Controller extends PageFlowController
       ^
[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:37: The specified exception-handler method handleIt3 contains a forward named "gotoError" which conflicts with a forward in exception-handler handleIt2.
public class Controller extends PageFlowController
       ^
[LOCAL_PATH]\WEB-INF\.tmpbeansrc\PF_ExceptionHandlerForward\Controller.java:46: Duplicate Forward tag on method begin (referenced from Catch) with name="gotoError".
   public Forward begin()
                  ^
7 errors
